---
title: "Chapter3"
output: word_document
---

# Aim 

Reproduce figures and tables for chapter 3

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


rainfall and PET

```{r}

# met file summary --------------------------------------------------------
source(here::here("Scripts/R/packages.R"))
source(here::here("Scripts/R/functions.R"))
path = here::here("04manuscript/refData/")
AD = read_dbtab(here("Data/ProcessedData/Richard.sqlite3"), "met_AshleyDene")

I12 = read_dbtab(here("Data/ProcessedData/Richard.sqlite3"), "met_Iversen12")
AD[, Clock.Today := as.Date(day, origin = paste0(year,"-01-01"))]
AD$Clock.Today %>% range()
I12 = I12[, Clock.Today := as.Date(day, origin = paste0(year,"-01-01"))
          ][Clock.Today %between% range(AD$Clock.Today)]
AD[, seasons := ifelse(Clock.Today >= "2010-06-02" & Clock.Today <= "2011-06-01",
                       "2010/11", 
                       ifelse(Clock.Today >= "2011-06-02" & Clock.Today <= "2012-06-01",
                              "2011/12", "2012"))]
I12[, seasons := ifelse(Clock.Today >= "2010-06-02" & Clock.Today <= "2011-06-01",
                       "2010/11", 
                       ifelse(Clock.Today >= "2011-06-02" & Clock.Today <= "2012-06-01",
                              "2011/12", "2012"))]
AD[, .(AnnualRain = sum(rain, na.rm = TRUE)), by = .(seasons)]
I12[, .(AnnualRain = sum(rain, na.rm = TRUE)), by = .(seasons)]

# All PET over 1997 to 2017
raw_PET <- fread(paste0(path, "/wgenf (3).genform1_proc"),
                 skip = 8, check.names = TRUE
                 )[, .(Date.NZST.,Amount.mm.)
                   ][, Date.NZST.:= as.Date(Date.NZST., format("%Y,%m,%d,%H"))]
raw_rain <- fread(paste0(path, "/wgenf (3).genform1_proc"),
                  skip = "Rain", check.names = TRUE
                  )[, .(Date.NZST.,Amount.mm.)
                    ][, Date.NZST.:= as.Date(Date.NZST., format("%Y,%m,%d,%H"))]
raw_PET_rain <- raw_PET[raw_rain, on = "Date.NZST."]
setnames(raw_PET_rain, c("Date","PET","Rainfall"))
# Check if the NIWA data has full date coverage
fulldates <- seq.Date(from = as.Date("1999-07-01"), to = as.Date("2017-06-30"), by = "day")
length(fulldates) == nrow(raw_PET_rain)

long_term_mean <- raw_PET_rain[, ':='(Year = gsub("-\\d{2}-\\d{2}", "", Date),
                    YearMonth = gsub("-\\d{2}$", "", Date),
                    MonthDay = gsub("\\d{4}-", "", Date))
                    ][, .(PET = mean(PET, na.rm = TRUE),
                          Rainfall = mean(Rainfall, na.rm = TRUE)), by = .(MonthDay)]

long_term_mean %>% 
  ggplot(aes(MonthDay)) +
  geom_point(aes(y = PET)) +
  geom_col(aes(y = Rainfall)) +
  theme(axis.text.x = element_text(angle = 90))

## Use long term mean to filled back the missing values in PET

raw_PET_rain <- merge(raw_PET_rain, long_term_mean, by = "MonthDay", suffixes = c("", "longterm"))
raw_PET_rain <- raw_PET_rain[, PET:=ifelse(is.na(PET), PETlongterm, PET)
             ][order(Date)
               ][, ':='(PETlongterm = NULL, Rainfalllongterm = NULL)]


raw_PET_rain[is.na(PET)]

raw_PET_rain %>% 
  ggplot(aes(Date)) +
  geom_point(aes(y = PET)) +
  geom_col(aes(y = Rainfall/10)) +
  theme(axis.text.x = element_text(angle = 90)) +
  ggtitle(length(unique(raw_PET_rain$Year))-1, "Seasons")

```
```{r}
raw_PET_rain <- group_in_season(raw_PET_rain)
```

```{r}
PET_rainfall_summary <- raw_PET_rain[, .(Rainall = sum(Rainfall, na.rm = TRUE),
                                         PET = sum(PET, na.rm = TRUE)), by = .(Season)]

kableExtra::kable(PET_rainfall_summary[order(PET)], digits = 0)

```
```{r}
long_term_mean[, .(monthlyRain = sum(Rainfall)), by = .(month = gsub("-\\d{2}","", MonthDay))] %>% 
  ggplot(aes(month, monthlyRain))+
  geom_col()
```
# Temperature and Radiation? 


```{r fig.width=14}
source(here::here("Scripts/R/packages.R"))
path = here::here("04manuscript/refData/wgenf (4).genform1_proc")
raw_Temp <-  fread(path,
       skip = "Station\t", check.names = TRUE
       )[, Date.NZST.:= as.Date(Date.NZST., format("%Y,%m,%d,%H"))]

raw_Rad <- fread(path,
                  skip = "Radiation", check.names = TRUE
                  )[, Date.NZST.:= as.Date(Date.NZST., format("%Y,%m,%d,%H"))]
raw_temp_rad <- raw_Rad[raw_Temp, on = "Date.NZST."]


raw_temp_rad <- raw_temp_rad[,.(Date = Date.NZST., Tmin.C.,Tmax.C., Radiation = Amount.MJ.m2.)
                    ][, Tmean := (as.numeric(Tmin.C.) + as.numeric(Tmax.C.))/2]
# Missing dates in the raw data 
wholeperiod <- data.table(Date = fulldates)
fulldates[!fulldates %in% temperature$Date]

raw_temp_rad <- raw_temp_rad[wholeperiod, on = "Date"]


chop_dates(raw_temp_rad)

group_in_season(raw_temp_rad)

long_term_mean <- raw_temp_rad[, .(Tmean = mean(Tmean, na.rm = TRUE)), 
                              by = .(MonthDay)]

long_term_mean %>% 
  ggplot(aes(MonthDay)) +
  geom_point(aes(y = Tmean)) +
  theme(axis.text.x = element_text(angle = 90))

## Use long term mean to filled back the missing values in PET

raw_temp_rad <- merge(raw_temp_rad, long_term_mean, by = "MonthDay", suffixes = c("", "longterm"))
raw_temp_rad <- raw_temp_rad[, Tmean:=ifelse(is.na(Tmean), Tmeanlongterm, Tmean)
             ][order(Date)
               ][, ':='(Tmeanlongterm = NULL)]
raw_temp_rad[is.na(Tmean)]
raw_temp_rad %>% 
  ggplot(aes(Date)) +
  geom_point(aes(y = Tmean), color = "grey80") +
  geom_smooth(aes(y = Tmean), span = 0.25) +
  theme(axis.text.x = element_text(angle = 90)) +
  ggtitle(length(unique(raw_temp_rad$Year))-1, "Seasons")

```


# Calculate the bucket size for each site

```{r}
source("../Scripts/R/packages.R")
source("../Scripts/R/functions.R")
id_vars <- c("Experiment", "SowingDate", "Clock.Today")

loadd(water)
loadd(starts_with("SW"))
loadd(value_vars)
water[, lapply(.SD, mean, na.rm = TRUE), by = id_vars, .SDcols = "SWC" # average 4 reps
                   ][, unlist(lapply(.SD, max_min), recursive = FALSE), by = .(Experiment), .SDcols = "SWC"
                     ][, PAWC := SWC.DUL - SWC.LL][]
```


# Illustrate mcp

```{r}
source("../Scripts/R/packages.R")
source("../Scripts/R/functions.R")
dbpath = "../Data/ProcessedData//Richard.sqlite3"
water = read_dbtab(path = dbpath)
long = melt(water[,SWC:=NULL], 
     id.vars = c("Experiment", "Clock.Today", "SowingDate", "DAS","Rep", "Plot","Season", "Seed"),variable.factor = FALSE)
long[, variable:= as.numeric(gsub("\\D","",variable))][]

long %>% 
    ggplot(aes(DAS, value)) +
  geom_point(color = "grey80") +
  facet_grid(variable ~ Experiment , scales = "free") +
  geom_smooth(method = "loess", color = "#ff0000", span = 0.25, se = FALSE)+ 
  theme_water() +
  ylab("Soil Water Content (mm)")
ggsave("../05figures/DecideNumberofCPs.png", dpi = 300, height = 5, width = 7)
```







