---
title: "1. Debug targets"
output: html_document
---

```{r setup, include=FALSE}
source("R/packages.R")
source("r/functions.R")
library(targets)
```


# Debug couldn't find objects

```{r}
tar_load("data_SW")
tar_load("value_vars")
tar_load("id_vars")
doDUL_LL_range(SW = data_SW)
filter_datemax(SW_mean = tar_read("SW_mean"), "max", id.vars = id_vars)
```
# Inspect ranges

```{r fig.height=10}
tar_load("DUL_LL_range")
tar_load("data_SW")
tar_load("value_vars")
tar_load("id_vars")
DUL_LL_range
tar_load("SW_mean")
SW_mean


range_check <- function(DT, range, layer, boundry = c("DUL","LL")){
  cols <- c("Experiment", "Clock.Today", "SowingDate", layer)
  DT <- DT[,..cols]
  yval <- paste0("`",layer,"`")
  P <- DT[,..cols] %>% 
    ggplot(aes_string("Clock.Today", yval)) + 
    geom_point() +
    facet_grid(SowingDate  ~ Experiment) 
  if(boundry =="LL"){
    P <- P + 
      geom_point(data = range[Depth ==layer], aes(Clock.Today.LL, SW.mean.LL),  color ="red", size = 5)
  } else if (boundry == "DUL"){
    P <- P + 
      geom_point(data = range[Depth ==layer], aes(Clock.Today.DUL, SW.mean.DUL),  color ="red", size = 5)
  } else{
    print("Don't know what to draw. DUL or LL")
  }
  return(P)
  
}
range_check(SW_mean, DUL_LL_range, "SW(2)", boundry = "DUL")
range_check(SW_mean, DUL_LL_range, "SW(2)", boundry = "LL")



```
It is not ideal to have a DUL from the end of the experiments. 
need to constrain the period 
**action** - modify the DUL and LL finder to lock the period. 

LL seems not the lowest since we constrian the period. 
maybe the end of June is good?
```{r fig.height=10}


range_check(SW_mean, DUL_LL_range, "SW(1)", boundry = "LL")
```

```{r, fig.height=14, fig.width=9}
Soil_char <- DUL_LL_range[,Depth:= as.integer(gsub("\\D", "", Depth))
             ][, .(Experiment, SowingDate, Depth, SW.mean.DUL, SW.mean.LL,
                   Low.DUL, High.DUL, Low.LL, High.LL)] 


DUL_LL_range[SowingDate %in% paste0("SD", 1:5)]%>% 
  ggplot(aes(y = Depth))+
  geom_point(aes(x = SW.mean.DUL)) +
  geom_point(aes(x = SW.mean.LL)) +
  geom_errorbar(aes(xmin = SW.mean.DUL - SW.sd.DUL, xmax = SW.mean.DUL + SW.sd.DUL))+
  geom_point(aes(x = Low.DUL), color = "red") +
  geom_point(aes(x = High.DUL), color = "blue") +
  geom_errorbar(aes(xmin = SW.mean.LL - SW.sd.LL, xmax = SW.mean.LL + SW.sd.LL))+
  geom_point(aes(x = Low.LL), color = "red") +
  geom_point(aes(x = High.LL), color = "blue") +
  facet_grid(  SowingDate ~ Experiment , scales = "free_x") +
  scale_y_reverse() +
  theme_water()
  


DUL_LL_range[SowingDate %in% paste0("SD", 1:5)]%>% 
  ggplot(aes(x = Depth))+
  geom_point(aes(y = SW.mean.DUL))+
  geom_line(aes(y = SW.mean.DUL)) +
   geom_line(aes(y = SW.mean.LL))+
  # geom_point()+
  scale_x_reverse() +
  coord_flip() +
  geom_point(aes(y = SW.mean.LL)) +
  geom_errorbar(aes(ymin = SW.mean.DUL - SW.sd.DUL, ymax = SW.mean.DUL + SW.sd.DUL))+
  geom_point(aes(y = Low.DUL), color = "red") +
  geom_point(aes(y = High.DUL), color = "blue") +
  geom_errorbar(aes(ymin = SW.mean.LL - SW.sd.LL, ymax = SW.mean.LL + SW.sd.LL))+
  geom_point(aes(y = Low.LL), color = "red") +
  geom_point(aes(y = High.LL), color = "blue") +
  facet_grid(  SowingDate ~ Experiment , scales = "free_x") +
  theme_water()
```
# check met files 
```{r}
tar_load(starts_with("met"))
met_AshleyDene
met_Iversen12
tar_read("cumTT")
```

.Simulations.Slurp
.Simulations.SlurpMorris