---
title: "APSIM_edit_fun"
author: "Junqi Zhu and Jian Liu"
date: "`r Sys.Date()`"
output: html_document
---

# Protocol

- Load data from sqlite   
- Set constants. e.g. colours and keys  
- Set target  
    Key outcomes:   
    - Initial soil water content[Initial soil water]      
    - A set of DUL[DUL AND LL]  
    - A set of LL[DUL AND LL]  
- Calculation and summarising  
- Joining[Combine Soil Paras]  
- Set up directory structure[Set directory structure]  
- Invoke **Edit**  [Invoke Apsimx]  


```{r setup, include=FALSE}
options(scipen=999)
  

knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE,
                      fig.align = "center", 
                      fig.width = 10, fig.height = 7, dpi = 300)
#Constants
outlier.colour = "#ff0000"
source("R/packages.R")

```

```{r}
water = read_dbtab("../03processed-data/Richard.sqlite3")
biomass = read_dbtab("../03processed-data/Richard.sqlite3", table = "biomass")

```

```{r}
AD = water[Experiment == "AshleyDene"]
AD_biomass = biomass[Experiment == "AshleyDene" & Seed == "CS"]

AD_sum = AD[, .(swc = mean(SWC, na.rm = TRUE)), by = .(Clock.Today, Experiment, SowingDate)]
AD_yield = AD_biomass[,.(yield = mean(Total.DM, na.rm = TRUE)), by = .(Clock.Today, Experiment, SowingDate)]


```
```{r}
AD_sum[SowingDate == "SD1"] %>% 
  ggplot(aes(Clock.Today, swc))+
  geom_line()
```

```{r}
AD_yield[SowingDate == "SD1"] %>% 
  ggplot(aes(Clock.Today, yield)) +
  geom_line()

```

