---
title: "Data_integration"
author: "Frank" 
date: "`r sys.Date()`"
output:  html_document

---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
source("R/packages.R")
source("R/functions.R")
```


## Read prediction results

```{r}
dbs = list.files("../03processed-data/apsimxLucerne/", "*.db$", full.names = TRUE)
dt =  read_dbtab(dbs, table = "Report")
dt[, (c("CheckpointID", "Zone")):= NULL]
dt
```


## Read the obersvations 

**WATER**
```{r}
SWC = readd(SWC_mean)
```



```{r}
loadd(starts_with("SW"))
water = merge.data.table(SW_mean, SWC_mean, by = c("Experiment", "SowingDate", "Clock.Today"))
biomass_obs = biomass[Seed == "CS", .(Height, LAI = LAImod,  Total.DM),
                      by = .(Experiment, SowingDate, Clock.Today)
                    ][, unlist(list(lapply(.SD, mean, na.rm = TRUE)), 
                               recursive = FALSE), 
                      by = .(Experiment, SowingDate, Clock.Today)
                      ][, Clock.Today := as.Date(Clock.Today)]
biomass_obs = biomass_obs[Clock.Today > "2011-11-30" & 
                            Clock.Today < "2012-03-01" & 
                            Experiment == "AshleyDene", k:= 0.66
                          ][, k := ifelse(is.na(k), 0.94, k)
                            ][, LightInterception := 1 - exp(-k*LAI)
                              ][, Height := Height * 10
                                ][, Height := ifelse(is.nan(Height), NA, Height)]
whole = rbindlist(list(water, biomass_obs), fill = TRUE, use.names = TRUE)

whole[, ':='(SimulationName = paste0(Experiment, "SowingDate", SowingDate))]
setcolorder(whole, c("SowingDate","SimulationName"))
whole = whole[!(Experiment == "Iversen12" & SowingDate %in% c("SD9","SD10"))]
write.xlsx(whole, "../03processed-data/20200630Whole.xlsx", sheetName = "Observed")

```



### Old work - probably no use in the future

```{r}
con <- dbConnect(SQLite(), "../03processed-data/Richard.sqlite3")
dbListTables(con)
biomass <- dbReadTable(con, "biomass") %>% 
  as.data.table()
water <- dbReadTable(con, "SoilWater", check.names = FALSE) %>% 
  as.data.table()
dbDisconnect(con)

# Fix the date 
biomass[, Date := as.Date(Date)]
water[, Date := as.Date(Date)]
```


```{r second attempt}
key_vars <- colnames(biomass)[c(2:7, 24:26)]
group_vars <- c("Site", "Date", "Season", "Sowing.Date")

# No need to convert unit. All DM in apsimNG are kg DM/ha
total_dm <- copy(biomass)[, ..key_vars # select the necessary vars
                          ][, lapply(.SD, function(x) mean(x, na.rm = TRUE)), # calculate the mean
                            .SD = key_vars[7:9],
                            by = group_vars
                            ][Total.DM != 0]

# Get colnames 
value_vars <- grep("SW.+", colnames(water), value = TRUE)
# Calculate the mean over replicates 
water_sum <- copy(water)[, lapply(.SD, function(x) mean(x, na.rm = TRUE)), # calculate the mean 
                         .SD = value_vars, by = group_vars]

# Stack two together
joined <- rbindlist(list(total_dm,water_sum), fill = TRUE)
# Modify in place. Type correction, SimName construction, 0 replace by NAs
joined <- joined[Site == "AshleyDene" # Look at AD only
                 ][, Date := as.Date(Date)
                     ][, SimulationName := paste0(Site, "SowingDate",Sowing.Date)
                       ][, lapply(.SD, function(x){
                         if(is.numeric(x)){
                           x = ifelse(x == 0, NA, x) # if numeric then replace 0 by NA
                           } else {
                             x # necessary one to keep all other type of columns
                             }
                         })]
setnames(joined, c("Date","Total.DM"),c("Clock.Today","ShootWt"))
joined[, ':=' (Site = NULL,
               Sowing.Date = NULL,
               Season = NULL)]
setcolorder(joined, "SimulationName")

```

**The harvest date and soil moisture measurement dates do not match, which is probably the reason that all observed data stack on top of each other that way**


```{r}
joined %>% 
  write.xlsx("../03processed-data/20200330_DM_SWC_sum.xlsx", sheetName = "Observed")
```

```{r }

path_apX <- "../01raw-data/ClimateAndObserved/Lucerne/"
xlsxs <- list.files(path_apX, pattern = "^\\w.+\\.xlsx")
xlsxs
```

```{r }
path <- "C:/Users/cflfcl/Dropbox/ApsimX_Lucerne/"
list.files(path, pattern = ".met")
l <- list.files(path, pattern = ".met", full.names = TRUE)
names(l) <- l
lapply(l, function(x)fread(x, skip = "()",nrows = 30))

```
