---
title: "20191023Data_explore"
output: github_document
---

## Aim 

1. improve the variable names to the same logic
2. combin `ObsAll` with Richard data

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE, fig.width = 8, fig.height = 6, dpi = 300)
source("../R/packages.R")
source("../R/functions.R")
```

```{r}
con <- dbConnect(SQLite(), "../Data/Lucerne/20191022_LucerneSWCwith_obs.db")
dbListTables(con)
```

```{r}
tab_compare <- con %>% 
  tbl( "PredictedObserved") %>% 
  collect()%>% 
  mutate(Clock.Today = as.Date(Clock.Today))

tab_compare  %>% 
  ggplot(aes(Observed.SWC, Predicted.SWC)) +
  geom_point() +
  theme_water()

tab_sims <- con %>% 
  tbl("_Simulations") %>% 
  collect()%>% 
  mutate(Site = gsub("SowingDate.+|Defoliation|Water.+", "", Name))
tab_sims_compare <- tab_sims %>% 
  right_join(tab_compare, by = c("ID" = "SimulationID" )) 
tab_sims_compare %>% 
  ggplot(aes(Observed.SWC, Predicted.SWC, color = Site)) +
  geom_point(size = 2.5) +
  theme_water() +
  scale_colour_viridis_d(option = "G") +
  theme(legend.position = c(.85, .2),
        legend.background = element_blank(),
        plot.margin = margin(2, 4, 2, 2, "mm")) +
  geom_abline(color = "red", size = 1) +
  scale_y_continuous(expand = c(0,0))+
  scale_x_continuous(expand = c(0,0))
  ggtitle("The scatter of predicted ~ observed SWC values")

ggsave("../imgs/SWC_in_profile_pred_obs_mm.png", height = 7, width = 11)


 tab_sims_compare %>% 
   select(Clock.Today, diff.SWC = `Pred-Obs.SWC`, Site) %>%
   filter(!is.na(diff)) %>%
   ggplot(aes(Clock.Today, diff.SWC, color = Site)) +
   geom_point(size = 2.5) +
   theme_water() +
   scale_colour_viridis_d(option = "G") +
   scale_x_date(date_breaks = "2 year", date_labels = "%Y", name = "") +
   theme(legend.position = c(.70, .8),
         legend.background = element_blank()) +
   scale_shape_manual(values=c(20:9)) +
   ggtitle("The variation of the difference between\r\nobserved and predicted SWC values")
 
ggsave("../imgs/diff_SWC_in_profile_mm.png", height = 7, width = 11)

```

