---
title: "kl estimation "
author: "jian (AKA Frank) liu"
date: "`r Sys.Date()`"
output: html_document
---

# Aim

EDA on root depth with SWC profile 


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE,
                      fig.align = "center", fig.width = 10, fig.height = 7, dpi = 300)
#Constants
outlier.colour = "#ff0000"
source("R/packages.R")
source("R/functions.R")
```


```{r}
loadd(starts_with("pred_obs"))
```
```{r}
pred_obs_pred_SW_Site_SD_Iversen12_SD3_long_obs_SW_Iversen12_SD3
cf = 2300/max(pred_obs_pred_SW_Site_SD_Iversen12_SD3_long_obs_SW_Iversen12_SD3$PSWC)
col_pred = "PSWC"
palette = rep("black", times = 3)
palette_named = setNames(palette,  c("PSWC", "RootDepth","SWC"))
palette_named[2:3] = c("blue", "red")
shapes = c(95, 124, 16)
shapes_named = setNames(shapes, c("PSWC", "RootDepth","SWC"))
unique(pred_obs_pred_SW_Site_SD_Iversen12_SD3_long_obs_SW_Iversen12_SD3[SimulationID == 25,.(Date, PSWC,SWC, RootDepth)]) %>% 
  ggplot(aes(Date)) +
  geom_line(aes(y = PSWC), size = 1, show.legend = NA) +
  geom_point(aes(y = SWC, color = "SWC", shape = "SWC"), show.legend = NA) +
  theme_water() +
  scale_x_date(date_labels = "%Y %b", date_breaks = "8 weeks") +
  geom_point(aes(y=RootDepth/cf, color="RootDepth", shape = 'RootDepth'), 
             size = 5,show.legend = NA)+
  scale_y_continuous(limits = range(pred_obs_pred_SW_Site_SD_Iversen12_SD3_long_obs_SW_Iversen12_SD3$PSWC), 
                     sec.axis = sec_axis(~ . *cf, name = "Root Depth")) +
   scale_shape_manual(name = "",values = shapes_named)+
  theme(legend.position = c(0.1,0.1)) +
  scale_color_manual(name = "",values = palette_named)
```
```{r}
autoapsimx::plot_root(pred_obs_pred_SW_Site_SD_Iversen12_SD3_long_obs_SW_Iversen12_SD3, "../05figures/test")
```

```{r}
path = "../03processed-data/apsimxFiles/ModifiedSKL_0.01AshleyDeneSD1.db"
report = read_dbtab(path, "Report")
obs = readd(SWC_mean)
obs_sw = readd(SW_mean)
obs_ADSD1 = obs[Experiment == "AshleyDene" & SowingDate == "SD1"]
obs_sw_ADSD1 = obs_sw[Experiment == "AshleyDene" & SowingDate == "SD1"]
obs_ADSD1 %>% 
  ggplot(aes(Clock.Today, SWC, color = "PSWC")) +
  # geom_line(size = 1) +
  geom_point()
```
## Subset the preds

```{r}
pred_swc_SD2 <- report[,.(Date = as.Date(Date), SimulationID,KLR, RFV, SKL, k, 
                          LAI, Height, RootDepth, `SW(1)`,PSWC)][order(SimulationID)]
```

```{r, fig.height=10,fig.width=10}
```


```{r, fig.height=10,fig.width=15}
loadd(starts_with("bestfitlayerkls_pred_SW"))
```


```{r, fig.height=7,fig.width=10}
bestfitlayerkls_pred_SW_AshleyDene_SD1[, Source:=basename(Source)]
cf = 2300/max(bestfitlayerkls_pred_SW_AshleyDene_SD1$PSWC)
col_pred = "PSWC"
palette = rep("black", times = 3)
palette_named = setNames(palette,  c("PSWC", "RootDepth","SWC"))
palette_named[2:3] = c("blue", "red")

bestfitlayerkls_pred_SW_AshleyDene_SD1 %>% 
  ggplot(aes(Date, PSWC, color = "PSWC")) +
  geom_line(size = 1) +
  geom_point(data = obs_ADSD1, aes(x = Clock.Today, y = SWC, color = "SWC")) +
  theme_water() +
  scale_x_date(date_labels = "%Y %b", date_breaks = "8 weeks") +
  geom_point(aes(y=RootDepth/cf, color="RootDepth"))+
  scale_y_continuous(limits = range(bestfitlayerkls_pred_SW_AshleyDene_SD1$PSWC), 
                     sec.axis = sec_axis(~ . *cf, name = "Root Depth")) +
  theme(legend.position = c(0.1,0.1)) +
  scale_color_manual(values = palette_named)
```
```{r fig.height=20}
pred = bestfitlayerkls_pred_SW_AshleyDene_SD1 %>% 
  melt(value.name = "pred_VWC",
       measure.vars = readd(value_vars), 
       variable.name = "Depth",
       variable.factor = FALSE)

obs = obs_sw_ADSD1 %>% 
  melt(value.name = "obs_VWC",
       measure.vars = readd(value_vars), 
       variable.name = "Depth",
       variable.factor = FALSE)
dt=merge(pred,obs, by.x = c("Date", "Experiment", "SowingDate","Depth"),
                     by.y = c("Clock.Today","Experiment", "SowingDate", "Depth"),
                     all.x = TRUE)
dt[, Depth := forcats::fct_relevel(as.factor(Depth), paste0("SW(",1:22, ")"))]
point_size = 1
col_pred = "pred_VWC"
palette = rep("black", times = 2)
palette_named = setNames(palette,  c("pred_VWC", "obs_VWC"))
palette_named[2] = c("red")
dt %>% 
  ggplot(aes(Date)) +
        geom_point(aes(y = pred_VWC,  color = "pred_VWC"), size = point_size) +
        geom_point(aes(y = obs_VWC, color = "obs_VWC" ), size = point_size) +
        facet_grid( reformulate( ".", "Depth")) +
        ggtitle(paste0(unique(pred$Experiment), unique(pred$SowingDate))) +
        scale_x_date(date_labels = "%Y %b", date_breaks = "4 weeks") +
        scale_color_manual(name = "", values = palette_named) +
        theme_water() +
        theme(legend.position = "top",
              axis.text.x = element_text(angle = 30, hjust = 1))
```


```{r, fig.height=10,fig.width=15}
bestfitlayerkls_pred_SW_AshleyDene_SD1[, Source:=basename(Source)]
p1 = bestfitlayerkls_pred_SW_AshleyDene_SD1 %>% 
  ggplot(aes(Date, PSWC)) +
  geom_point() +
  theme_water()
p2 = bestfitlayerkls_pred_SW_AshleyDene_SD1 %>% 
  ggplot(aes(Date)) +
  geom_point(aes(y = RootDepth), shape = "|") +
  theme_water()
cowplot::plot_grid(p1 + 
                     theme(axis.text.x.bottom = element_blank(),
                           axis.title.x.bottom = element_blank()), NULL, p2, 
                   align = "v")
pred = bestfitlayerkls_pred_SW_AshleyDene_SD1 %>% 
  melt(value.name = "pred_VWC",
       measure.vars = readd(value_vars), 
       variable.name = "Depth",
       variable.factor = FALSE)
pred[, Depth := forcats::fct_relevel(as.factor(Depth), paste0("SW(",1:22, ")"))]
point_size = 0.5
col_pred = "pred_VWC"
# palette = rep("grey", times = 2)
# palette_named = setNames(palette,  c(col_pred, col_obs))
# palette_named[2] = "red"
p3 = pred %>% 
  ggplot(aes(Date)) +
        geom_point(aes(y = get(col_pred)), size = point_size) +
        
        facet_grid( reformulate( ".", "Depth")) +
        ggtitle(paste0(unique(pred$Experiment), unique(pred$SowingDate))) +
        scale_x_date(date_labels = "%Y %b", date_breaks = "4 weeks") +
        # scale_color_manual(name = "", values = palette_named) +
        theme_water() +
        theme(legend.position = "top",
              axis.text.x = element_text(angle = 30, hjust = 1))
p4 = cowplot::plot_grid(p1 + 
                          theme(axis.text.x.bottom = element_blank(),
                                axis.title.x.bottom = element_blank()), NULL, p2, 
                   align = "v")
cowplot::plot_grid(p4, NULL, p3, nrow = 1, rel_widths = c(2,-1,1))

```


```{r, fig.height=10,fig.width=10}
p1 = pred_swc_SD2[SimulationID == 1] %>% 
  ggplot(aes(Date, PSWC)) +
  geom_point() +
  # geom_point(aes(y = RootDepth), shape = "|") + 
  facet_wrap(~ SimulationID)
p2 = pred_swc_SD2[SimulationID == 1] %>% 
  ggplot(aes(Date)) +
  geom_point(aes(y = RootDepth), shape = "|")
library(gtable)
library(grid) # low-level grid functions are required
g1 <- ggplotGrob(p1)
# g1 <- gtable_add_cols(g1, unit(0,"mm")) # add a column for missing legend
g2 <- ggplotGrob(p2)
g <- rbind(g1, g2, size="first") # stack the two plots
g$widths <- unit.pmax(g1$widths, g2$widths) # use the largest widths
# center the legend vertically
g$layout[grepl("guide", g$layout$name),c("t","b")] <- c(1,nrow(g))
grid.newpage()
grid.draw(g)
print(g)
```