---
title: "Chapter4"
author: "jian (AKA Frank) liu"
date: "17/01/2021"
output:
  html_document:
    df_print: paged
  word_document:
    reference_docx: dissertationTemplate.docx
always_allow_html: yes
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE,
                      fig.align = "center", fig.width = 10, fig.height = 7, 
                      dpi = 300)
options(scipen = 999)
#Constants
outlier.colour = "#ff0000"
source(here::here("02Scripts/R/packages.R"))
source(here::here("02Scripts/R/functions.R"))
path_richard <- "C:/Users/cflfcl/Dropbox/Data/APSIM_Sim.xlsx"
id_vars <- c("Experiment", "SowingDate", "Clock.Today", "DAS")

data_sw <- read_Sims(path = path_richard)

value_vars <-  grep("SWmm\\.\\d.", colnames(data_sw), value = TRUE)
sw_mean_new <- colwise_meanSW(data_sw)

# Colour p
blues <- c("#0f5e9c",
           "#2389da",
           "#1ca3ec",
           "#5abcd8",
           "#74ccf4")
names(blues) <- blues 
ggplot(data.frame(x = blues, y = 1),aes(x, y, fill = x)) +
  geom_col() +
  scale_fill_manual(name = "", values = blues)+
  theme_void()

magicDate <- "2011-06-25"
theme_frnl <- function(){
  theme_bw() +
  theme(strip.background = element_blank(),
        strip.placement = "outside",
        plot.background = element_rect(inherit.blank = T),
        plot.caption = element_text(hjust = 0.5, size = rel(2)),
        legend.direction = "horizontal",
        legend.title = element_blank(),
        legend.key = element_blank(),
        legend.position = "bottom",
        panel.background = element_rect(fill = "white",colour = "grey"))
}
```


### long term radiation and temp

manually download a montly weather file from cliflo
```{r}
monthly <- fread(input = "../../01Data/ClimateAndObserved/wgenf (1).txt", skip = "Stats: Monthly")
monthlyRian_PET <- monthly[-(1:2), .(Date = `Mon-YYYY(local)`, variable = `Stat Code`, 
            value = `Stat Value`)
        ][, ':=' (year = as.integer(gsub("\\D", "", Date)),
                        month = gsub("-.+", "", Date), 
                        variable = ifelse(variable == 0, "Rainfall", "PET"))
          ][, Date := as.Date(paste0("01-", Date), tryFormats = "%d-%b-%Y")] 

seasonal <- group_in_season(monthlyRian_PET)
seasonal[Season != "2021/2022", .(sum(value)) , by = .(Season, variable)
         ][, .(mean(V1), sd(V1), range(V1)), by = .(variable)]
seasonal[, .(value = mean(value)), by = .(variable, month)
         ][, Date := as.Date(paste0("2020-", month, "-01"), format = "%Y-%b-%d")]%>% 
  dcast(Date  ~ variable) %>% 
  ggplot(aes(Date)) +
  geom_line(aes(y = PET)) +
  geom_col(aes(y = Rainfall)) +
  theme_frnl()
monthlyRian_PET %>% 
  ggplot(aes(Date, value, color = variable)) +
  geom_line() +
  theme_frnl()
```


```{r}
seasonal[Season == "2011/2012"] %>% 
  dcast(Date  ~ variable) %>%  
  ggplot(aes(Date)) +
  geom_line(aes(y = PET)) +
  geom_col(aes(y = Rainfall)) +
  theme_frnl()
```


```{r}
# devtools::install_github("ropensci/clifro")

# Ed wants to extract  mint, maxt, rad and rain.
# from 1981 ~ present 

library(clifro)
library(data.table)
library(lubridate)
cf_find_station("lincoln", search = "name") # not working any more

lincoln = cf_station(17603)
me <-  cf_user("frank0434",password = getPass::getPass())
my.dts <- cf_datatype(c(4, 5), #temperature, radiation - 1,2,3 in this template
                      c(2, 2),
                      list(2, 2), # hourly and daily
                      c(NA,NA))


cf.datalist <- cf_query(user = me,
                        datatype = my.dts,
                        station = lincoln,
                        start_date = "2011-07-01 00",
                        end_date = "2012-07-01 00")

# saveRDS(cf.datalist, file = "../../_targets/objects/cf.datalist.rds")
source(here::here("02Scripts/R/functions", "cliflo_list_converter.R"))

# converting into the df --------------------------------------------------
# cf.datalist <- readRDS(file = "../../_targets/objects/cf.datalist.rds")

list_converter(cf.datalist)
    # dt <- as.data.table(cf.datalist,stringsAsFactors = F)
    # colnames(dt) <- gsub(pattern = "\\(|\\/","_",colnames(dt))
    # colnames(dt) <- gsub(pattern = "\\)","",colnames(dt))
    # 
    # dt <- dt[,Date:= as.Date(lubridate::ymd_hms(Date_local))]


# period <- data.table(Date = seq.Date(as.Date("1999-07-01"),
#                                      as.Date("2019-07-01"),
#                                      by = 1),
#                      Julian = seq(julian(ymd("2019-07-01"),
#                                          origin = ymd("1999-07-01"))))[,                                                                       md:=gsub("\\d{4}-","",Date)]

```

```{r}# fix NAs
dt <- dt_Max_min20110701to20120701
dt[is.na(Tmean_C), Tmean_C := (Tmin_C + Tmax_C) / 2
   ][is.na(Tmin_C), Tmin_C := Tmean_C * 2 - Tmax_C]
# Check any NAS
dt[is.na(Tmean_C)]; dt[is.na(Tmin_C)];dt[is.na(Tmax_C)]

dailyTT <- weaana::thermalTimeHourly(dt$Date_local, 
                                     temperature = dt$Tmean_C,
                                     x_temp = c(1,15,30,40), # LUCERNE CARDINAL 
                                     y_temp = c(0,10,25,0)) # EFFECTIVE TT
dailyTT <- as.data.table(dailyTT)
setnames(dailyTT, "date", "Date")
dailyTT <- group_in_season(as.data.table(dailyTT))
dailymean <- dt[, Date := as.Date(Date_local, tz= "NZ" )
                ][, .(dailymean = mean(Tmean_C, na.rm = TRUE)), by = .(Date)]
range(dailymean$dailymean)
sum(dailyTT$value)
dailyTT[!is.na(Season)
        ][, gdd := cumsum(value)][dailymean, on = "Date"] %>% 
  ggplot() +
  geom_area(aes(Date,dailymean,fill = "grey"))+
  geom_point(aes(Date,gdd/200,color = "red"))+
  # geom_line(aes(Date,GDD_10_avg/100,color = "grey"))+
  scale_fill_manual(values = "grey", labels = "Daily Mean Temperature (°C)")+

  scale_y_continuous(expand = c(0,0),limits = c(0,20),
                     name = "Daily Mean Temperature (°C)",
                     sec.axis = sec_axis(~.*200, name = "Cumulative Growing Degree Days (°Cd)"))+
  scale_color_manual(values = c(red ="red"),
                     labels= c(red = "Seasonal cumulative Growing Degree Days (°Cd)"))+
  scale_x_date(expand = c(0,0))+
  theme_frnl() +
  theme(text = element_text(size = 16)) +
  guides(
    fill = guide_legend(order = 1))
ggsave("Figures/ch3_cardinalTT.png", dpi = 300, width = 10, height = 7)


```
2011/2012 radiation 

```{r}
dt <- dt_Radiation20110701to20120701
dt[is.na(Amount_MJ_m2)]
dailymean <- dt[, Date := as.Date(Date_local, tz= "NZ" )
                ][, .(Amount = sum(Amount_MJ_m2)), by = .(Date)
                  ][, Cum_Radiation := cumsum(Amount)]
dailymean %>% 
  ggplot() +
  geom_area(aes(Date,Amount,fill = "grey"))+
  geom_point(aes(Date,Cum_Radiation/200,color = "red"))+
  # geom_line(aes(Date,Cumulative_Radiation_10_avg/100,color = "grey"))+
  scale_y_continuous(expand = c(0,0),bquote("Daily Radiation "~(MJ ~m^-2)), 
                     sec.axis = sec_axis(~.*200, name = bquote("Cummulative Radiation "~(MJ ~m^-2))))+
  scale_color_manual(values = c(red ="red"),
                     labels= c(red = "Cummulative Radiation"))+
  scale_fill_manual(values = "grey", labels = "Daily Radiation")+
  scale_x_date(expand = c(0,0))+
    theme_frnl()+

  theme(text = element_text(size = 16)) 
  
ggsave("Figures/ch3_2011_2012rad.png", dpi = 300, width = 10, height = 7)

```

$$T^n_{diurnal} = [(0.931 + 0.114n - 0.0703n^2 + 0.0053n^3) \times (T_{max} - T_{min})] + T_{min}$$
remotes::install_github('byzheng/weaana')
this package has temperature calculation based on met file format 



```{r}
# Calculate the 3hour temperature
hour <- seq(1, 8)
frac <- 0.92105 + 0.1140 * hour - 0.0703 * 
  hour * hour + 0.0053 * hour * hour * hour
dt <- dt_Max_min19990701to20190630[, .(Date_local, Tmax_C, Tmin_C)]
# Check if any abnormal records of min temp is greater than max temp
pos <- dt$Tmax_C < dt$Tmin_C
sum(pos, na.rm = TRUE)
# an old code to swap those values
# metdf_DT <- metdf_DT[pos,c("maxt","mint"):= .(mint,maxt)]
# https://simplmodl.wordpress.com/2014/01/31/a-simple-way-to-repeat-replicate-or-explode-data-table-rows-in-r/
dt <- dt[rep(seq(1, .N), length(hour))][order(Date_local)]
dt[, ]

```

```{r}
cftemp10_avg <- dt[,.(Date = Date_local, max = Tmax_C,min = Tmin_C)
                   ][,':='(Date = gsub("\\d{4}-","",as.Date(Date)),
                           Tmean = (max+min)/2)][order(Date)
                                                 ][,.(Tmean_10 = mean(Tmean,na.rm = T)), by = .(Date)]
cftemp10 <- merge(period,cftemp10_avg,by.x = "md",by.y = "Date")[order(Date)]


Temp_NA_index <- which(is.na(cftemp10$Tmean))
temp_gdd <- group_in_season(cftemp10)[,GDD_10_avg := cumsum(Tmean_10 - 1), by = .(Season)][]
          
temp_gdd[, list(temp = mean(Tmean_10, na.rm = TRUE), 
                gdd = mean(GDD_10_avg)), by = .(md)
         ][, Date := as.Date(paste0("2011-", md))] %>% 
  ggplot() +
  geom_area(aes(Date,temp,fill = "grey"))+
  geom_point(aes(Date,gdd/200,color = "red"))+
  # geom_line(aes(Date,GDD_10_avg/100,color = "grey"))+
  scale_fill_manual(values = "grey", labels = "Daily Mean Temperature (°C)")+

  scale_y_continuous(expand = c(0,0),limits = c(0,20),
                     name = "Daily Mean Temperature (°C)",
                     sec.axis = sec_axis(~.*200, name = "Cumulative Growing Degree Days (°Cd)"))+
  scale_color_manual(values = c(red ="red"),
                     labels= c(red = "Seasonal cumulative Growing Degree Days (°Cd)"))+
  scale_x_date(expand = c(0,0))+
  theme_frnl() +
  theme(text = element_text(size = 16)) +
  guides(
    fill = guide_legend(order = 1))
ggsave("Figures/ch3_temp.png", dpi = 300, width = 10, height = 7)

temp_gdd[, list(temp = mean(Tmean_10, na.rm = TRUE), 
                gdd_sd = sd(GDD_10_avg),
                gdd = mean(GDD_10_avg)), by = .(md)
         ]


range(temp_gdd$GDD_10_avg)
```

### radiation

```{r}
cfrad10_avg <- dt_Radiation19990701to20190630[,.(Date_local, Amount = Amount_MJ_m2)
                                               ][,Date := gsub("\\d{4}-","",as.Date(Date_local))
                                                 ][order(Date)
                                                   ][,.(Amount_10 = mean(Amount,na.rm = T)),by = .(Date)]
cfrad10_avg <- merge(period,cfrad10_avg,by.x = "md",by.y = "Date")[order(Date)]

rad <- group_in_season(cfrad10_avg)[,Cum_Radiation := cumsum(Amount_10), by = .(Season)][]
          
rad[, list(Amount = mean(Amount_10, na.rm = TRUE),
                Cum_Radiation = mean(Cum_Radiation, na.rm = TRUE) ), by = .(md)
         ][, Date := as.Date(paste0("2011-", md))] %>% 
  ggplot()+
  geom_area(aes(Date,Amount,fill = "grey"))+
  geom_point(aes(Date,Cum_Radiation/200,color = "red"))+
  # geom_line(aes(Date,Cumulative_Radiation_10_avg/100,color = "grey"))+
  scale_y_continuous(expand = c(0,0),"Daily Radiation MJ " ~m^-2, 
                     sec.axis = sec_axis(~.*200, name = "Cummulative Radiation MJ " ~m^-2))+
  scale_color_manual(values = c(red ="red"),
                     labels= c(red = "Cummulative Radiation"))+
  scale_fill_manual(values = "grey", labels = "Daily Radiation")+
  scale_x_date(expand = c(0,0))+
    theme_frnl()+

  theme(text = element_text(size = 16)) 
  
ggsave("Figures/ch3_rad.png", dpi = 300, width = 10, height = 7)

rad[, list(Amount = mean(Amount_10, na.rm = TRUE),
           cumrad_sd = sd(Cum_Radiation),
                Cum_Radiation = mean(Cum_Radiation, na.rm = TRUE) ), by = .(md)
         ]
$Amount %>% 
  range(na.rm = TRUE)


temp_gdd[, list(temp = mean(Tmean_10, na.rm = TRUE), 
                gdd_sd = sd(GDD_10_avg),
                gdd = mean(GDD_10_avg)), by = .(md)
         ]

```


### LEAR response to temp and photoperiod
```{r}


x = c(1, 15, 30, 40)
y = c(0, 10, 25, 0)
lab = c("T[b]", "T[i]", "T[o]", "T[m]")
df_tt <- data.frame(x =  x, y =  y, z = lab)
p_tt <- df_tt %>% 
  ggplot(aes(x, y )) +
  geom_line(size = 1.5) + 
  geom_text(aes( y = y +3, label =  bquote(.(z))), size = 12, nudge_x = 1, nudge_y = 1,
            parse = TRUE) +
  scale_y_continuous(expand = c(0,0), limits = c(0, 35))+
  scale_x_continuous(expand = c(0,0), limits = c(0, 43)) +
  theme_classic()+
  theme(panel.background = element_rect(fill = NA, colour = "black"),
        text = element_text(size = 16)) +
  labs( x = "Air Temperature (\u00B0C)", 
        y = "Thermal time (\u00B0Cd)")

a = c(8, 10, 16.5,  11.5, 12, 16.5)
b = c(0, 0.0056, 0.015,  0, 0.018, 0.02)
lab = c(rep("Decreasing", 3), rep("Increasing", 3))
df_pp <- data.frame(a , b , lab)
p_pp <- df_pp %>% 
  ggplot(aes(a , b)) +
  geom_line(size = 1.5) +
  scale_y_continuous(expand = c(0,0), limits = c(0, 0.025))+
  scale_x_continuous(expand = c(0,0), limits = c(7, 17), n.breaks = 7) +
  facet_wrap(~ lab) +
  theme_classic()+
  theme(panel.background = element_rect(fill = NA, colour = "black"),
        text = element_text(size = 16)) +
  labs( x = "Photoperiod (h)", 
        y = bquote("LEAR (m"^2~"/m"^2~" \u00B0Cd)") )

p_LEAR <- plot_grid(p_tt, p_pp, ncol = 1, align = "v", axis = "lr")
ggsave("Figures/ch3_LEAR.png",plot = p_LEAR,
       width = 7, height = 7, dpi = 320)
```

### RUE
```{r}
x = c(0	,18,30,40)
y = c(0,1.1,1.1,0)

df_rue <- data.frame(x , y)
p_rue <- df_rue %>% 
  ggplot(aes(x, y)) +
  geom_line(size = 1.5) +
  scale_y_continuous(expand = c(0,0), limits = c(0, 1.5))+
  scale_x_continuous(expand = c(0,0), limits = c(0, 42), n.breaks = 7) +
  
  theme_classic()+
  theme(panel.background = element_rect(fill = NA, colour = "black"),
        text = element_text(size = 16)) +
  labs( x = "Mean Air Temperature (\u00B0C)", 
        y = bquote("RUE (g DM MJ"^-1~")") )
p_rue
ggsave("Figures/ch3_rue.png",plot = p_rue,
       width = 7, height = 3.5, dpi = 320)

x = c(0,0.15,0.75,0.9,1)
y = c(0,0.4,0.75,1,1)
df_rue_fw <- data.frame(x , y)
p_rue_fw <- df_rue_fw %>% 
  ggplot(aes(x, y)) +
  geom_line(size = 1.5) +
  scale_y_continuous(expand = c(0,0), limits = c(0, 1.1))+
  scale_x_continuous(expand = c(0,0), limits = c(0, 1), n.breaks = 7) +
  
  theme_classic()+
  theme(panel.background = element_rect(fill = NA, colour = "black"),
        text = element_text(size = 16)) +
  labs( x = bquote("T/T"["D"]), 
        y = bquote("f"["stressed"]~"/f"["optimal"]) )
ggsave("Figures/ch3_rue_FW.png",plot = p_rue_fw,
       width = 7, height = 3.5, dpi = 320)

```

### Phyllochron
```{r}
a = c(10, 16.5,  10, 12, 16.5)
b = c(49, 35, 49,  31, 31)
lab = c(rep("Decreasing", 2), rep("Increasing", 3))
df_pp <- data.frame(a , b , lab)
p_pp <- df_pp %>% 
  ggplot(aes(a , b)) +
  geom_line(size = 1.5) +
  scale_y_continuous(expand = c(0,0), limits = c(30, 50))+
  scale_x_continuous(expand = c(0,0), limits = c(9, 18), n.breaks = 7) +
  facet_wrap(~ lab) +
  theme_classic()+
  theme(panel.background = element_rect(fill = NA, colour = "black"),
        text = element_text(size = 16),
        panel.spacing = unit(5, "mm")) +
  labs( x = "Photoperiod (h)", 
        y = bquote("Phyllochron (\u00B0Cd)") )
ggsave("Figures/ch3_phyllochron.png",plot = p_pp,
       width = 7, height = 3.5, dpi = 320)

```

### Water stress on phyllochron
```{r}
a=c(0, 0.5,  0.7, 1)
b=c(2, 2,  1, 1)
df_ph_fw <- data.frame(a, b)
p_ph_fw <- df_ph_fw %>% 
  ggplot(aes(a, b)) +
  geom_line(size = 1.5) +
  scale_y_continuous(expand = c(0,0), limits = c(0.8, 2.2))+
  scale_x_continuous(expand = c(0,0), limits = c(0,1.1)) +
  
  theme_classic()+
  theme(panel.background = element_rect(fill = NA, colour = "black"),
        text = element_text(size = 16)) +
  labs( x = bquote("T/T"["D"]), 
        y = bquote("f"["stressed"]~"/f"["optimal"]) )
ggsave("Figures/ch3_ph_fw.png",plot = p_ph_fw,
       width = 7, height = 3.5, dpi = 320)
```
### Heightchron
```{r}
a = seq(8, 16.5, by = 0.5)
b = 0.62 + 9766 * exp(a*-1)
df_height <- data.frame(a, b)
p_height <- df_height %>% 
  ggplot( aes(a,b))+
  geom_line(size = 1.5)+
  # scale_y_continuous(exp+
  scale_x_continuous(expand = c(0,0)) +
  
  theme_classic()+
  theme(panel.background = element_rect(fill = NA, colour = "black"),
        text = element_text(size = 16)) +
  labs( x = bquote("Photoperiod (h)"), 
        y = bquote("Heightchron ( ˚Cd mm "^-1~")") )
p_height
ggsave("Figures/ch3_p_height.png",plot = p_height,
       width = 7, height = 3.5, dpi = 320)
```


### Flowering?
```{r}
DT <- as.data.table(read_excel(path_richard, sheet = 2, skip = 9,
                               guess_max = 10000, .name_repair = "universal"))
pheno <- DT[Data == "Phenology"]
cols <- choose_cols(pheno)
pheno <- pheno[,..cols]
pheno %>% 
  ggplot(aes(Date, Fi_No)) +
  geom_point() +
  facet_wrap( Site ~ Sowing.Date)
## number 1 to 10 represent how many branches 
pheno[, Fi:=Fi/10]

dt <- pheno[, .(meanfi = mean(Fi, na.rm = TRUE)), 
            by = .(Site, Sowing.Date, Date)
            ][!is.nan(meanfi)]

dt %>% 
  ggplot(aes(Date, meanfi, color = Sowing.Date)) +
  geom_point() +
  facet_wrap( ~Site )


```

